### ISSUE TITLE
Please release a new version

### ISSUE THREAD

**Issue by tmaier** [max-favilli/tagmanager#229]
I've got aware that there is a bug in tagmanager, which has been fixed shortly after the release of 3.0.1 - exactly a year ago.

https://github.com/tmaier/tagmanager-rails/issues/6#issuecomment-63615146

As the [ruby gem](https://github.com/tmaier/tagmanager-rails) just follows official releases of tagmanager, this bug is not yet fixed for many users.
Please release a new version, so that I can also release a new version.

Thank you very much.

**Comment by max-favilli** [comment]
I am looking back at the code this week to publish a new version.

**Comment by max-favilli** [comment]
Released.
