### ISSUE TITLE
Demo for with twitter-typeahead doesn't allow adding Tags

### ISSUE THREAD

**Issue by jplehmann** [max-favilli/tagmanager#234]
On the demo page: http://welldonethings.com/tags/manager/v3

Under the example with twitter-typeahead, when one types something into the text box and presses enter it does not create a new tag box.  Instead you can see the "Tag" text show up beneath your typed text.  Using the cursor to select a displayed option does not create a new tag either.

**Comment by max-favilli** [comment]
docs.html was broken, fixed just now with 378890fc4aee2eeecf91f4dfaee8b1f350851b4a
