### ISSUE TITLE
Replace comma inside value before it goes to output or change output delimiter

### ISSUE THREAD

**Issue by decosvaldo** [max-favilli/tagmanager#255]
Hi, I have some strings that uses comma (,) inside them. This is causing the output to receive the value as duplicated when I send it to database.
What are my options here? Can I change this delimiter or format this value before it goes to the output with a escape character? E.g change a,b to a\,b

Thanks.

**Comment by BryanRice800** [comment]
can you encode the coma as \\,?

**Comment by decosvaldo** [comment]
Hi, didn't get it. What do you mean?
I need To modify the comma character (,) to something else or use something to replace it to make php escape it.
But on the container only.

Thanks

Obter o Outlook para Android<https://aka.ms/ghei36>



De: BryanRice800
Enviado: quarta-feira, 13 de dezembro 19:49
Assunto: Re: [max-favilli/tagmanager] Replace comma inside value before it goes to container or change container delimiter (#255)
Para: max-favilli/tagmanager
Cc: decosvaldo, Author


can you encode the coma as ,?

**Comment by BryanRice800** [comment]
I mean encode the coma, precede the commas with a backslash: `street 1\,address1, street2\, address2, etc`

**Comment by decosvaldo** [comment]
But how to that? Is there any method that allows that without affect the visual part for the user? I mean, encode that before write to container.

Thanks

Obter o Outlook para Android<https://aka.ms/ghei36>

________________________________

**Comment by BryanRice800** [comment]
The answer can vary a lot, you can do that from your back end or do it in javascript lopping through each of the options. the values in the select element would have the encoded version and the text would have the normal version.

**Comment by decosvaldo** [comment]
I really don't figure how can I replace inside commas without affect the correct commas inside the container.
Can you help me how to do that within the plugin action when tag is inserted?

Atenciosamente

Andre Luiz Paiz
________________________________
De: BryanRice800 <notifications@github.com>
Enviado: quinta-feira, 14 de dezembro de 2017 13:58
Para: max-favilli/tagmanager
Cc: decosvaldo; Author
Assunto: Re: [max-favilli/tagmanager] Replace comma inside value before it goes to container or change container delimiter (#255)


The answer can vary a lot, you can do that from your back end or do it in javascript lopping through each of the options. the values in the select element would have the encoded version and the text would have the normal version.

**Comment by decosvaldo** [comment]
Sorry, I've made a mistake. The destination object that I need to replace comma before it goes to is the OUTPUT, not the container.

**Comment by decosvaldo** [comment]
Fixed, I have found how to change the delimiter inside the tagmanager.js script. Maybe it can become a variable in the future.
